name: Trigger akto tests
 
on:
  workflow_dispatch:
    inputs:
        testRunId:
          default: "1"

  schedule:
    - cron: "0 0 */3 * *"

jobs:
  akto_cicd_test:
    runs-on: ubuntu-latest
    name: Test akto ci/cd
    steps:
      - uses: actions/checkout@v2
      # - uses: akto-api-security/run-scan@v1.0.3
      #   with:
      #     AKTO_DASHBOARD_URL: ${{vars.AKTO_DASHBOARD_URL}}
      #     AKTO_API_KEY: ${{vars.AKTO_API_KEY}}
      #     AKTO_TEST_ID: ${{ github.event.inputs.testRunId == '1' && vars.AKTO_TEST_ID || github.event.inputs.testRunId }}
      - run: bash ./.github/workflows/akto-cicd.sh
